name: little_strategy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.6.0

dependencies:
  analyzer: ^5.13.0
  flutter:
    sdk: flutter
  board_game:
    path: packages/features/board_game
  build_runner: ^2.4.13
  user_remote_repository:
    path: packages/user_remote_repository
  firebase_core: ^3.8.0
  game_repository:
    path: packages/game_repository
  storage_repository:
    path: packages/storage_repository
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6
  firebase_auth: ^5.3.3
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  flame: ^1.22.0
  logging: ^1.3.0
  game_info_repository:
    path: packages/game_info_repository
  lootbox_repository:
    path: packages/lootbox_repository
  confetti: ^0.8.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
