name: board_game
publish_to: none

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.18.1
  mocktail: ^1.0.4
  mockito: ^5.4.1
  build_runner: ^2.4.14
  fl_chart: ^0.60.0
  firebase_auth: ^5.3.3
  logging: ^1.1.0
  riverpod: ^2.3.0
  firebase_storage: ^12.3.6
  flutter_riverpod: ^2.3.0
  shared_preferences: ^2.1.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  cloud_firestore: ^5.5.1
  flame: ^1.5.0

  # Dépendances locales
  domain_entities:
    path: ../../domain_entities
  user_remote_repository:
    path: ../../user_remote_repository
  game_repository:
    path: ../../game_repository
  storage_repository:
    path: ../../storage_repository
  game_info_repository:
    path: ../../game_info_repository
  lootbox_repository:
    path: ../../lootbox_repository
  confetti: ^0.8.0
  animated_text_kit: ^4.2.2
  shimmer: ^2.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.0.3
  riverpod_annotation: ^2.6.1
  json_serializable: ^6.9.0
  utils:
    path: ../../utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  analyzer: ^6.5.0
  riverpod_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/sounds/
