name: board_game
publish_to: none

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  provider: ^6.1.2
  intl: ^0.19.0
  mocktail: ^1.0.4
  hive_test: ^1.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.13
  fl_chart: ^0.69.2
  firebase_auth: ^5.3.3
  logging: ^1.3.0
  riverpod: ^2.6.1
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  cloud_firestore: ^5.5.1
  flame: ^1.22.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Dépendances locales
  domain_entities:
    path: ../../domain_entities
  user_remote_repository:
    path: ../../user_remote_repository
  game_repository:
    path: ../../game_repository
  storage_repository:
    path: ../../storage_repository
  game_info_repository:
    path: ../../game_info_repository
  lootbox_repository:
    path: ../../lootbox_repository  
  confetti: ^0.8.0
  audioplayers: ^6.1.0
  lottie: ^3.3.0
  animated_text_kit: ^4.2.2
  shimmer: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
