// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBggNe6Z9vk-kRGf6TXtvtnh-UZCJxKAsI',
    appId: '1:489153684515:web:185542e222804f21fe3d96',
    messagingSenderId: '489153684515',
    projectId: 'little-strategy-6837a',
    authDomain: 'little-strategy-6837a.firebaseapp.com',
    databaseURL: 'https://little-strategy-6837a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'little-strategy-6837a.firebasestorage.app',
    measurementId: 'G-PGYEQ3HF38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByBjOSUKP_UenH0lJT_Vm1dShcOIUASWE',
    appId: '1:489153684515:android:49710c447f7c13f0fe3d96',
    messagingSenderId: '489153684515',
    projectId: 'little-strategy-6837a',
    databaseURL: 'https://little-strategy-6837a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'little-strategy-6837a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvGQGrmgjZoCa1ZRSKHdiuNawohHL0P7w',
    appId: '1:489153684515:ios:d3ff04a0fb18cfc1fe3d96',
    messagingSenderId: '489153684515',
    projectId: 'little-strategy-6837a',
    databaseURL: 'https://little-strategy-6837a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'little-strategy-6837a.firebasestorage.app',
    iosBundleId: 'com.example.littleStrategy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvGQGrmgjZoCa1ZRSKHdiuNawohHL0P7w',
    appId: '1:489153684515:ios:d3ff04a0fb18cfc1fe3d96',
    messagingSenderId: '489153684515',
    projectId: 'little-strategy-6837a',
    databaseURL: 'https://little-strategy-6837a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'little-strategy-6837a.firebasestorage.app',
    iosBundleId: 'com.example.littleStrategy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBggNe6Z9vk-kRGf6TXtvtnh-UZCJxKAsI',
    appId: '1:489153684515:web:732c4fa7aa1ac0b5fe3d96',
    messagingSenderId: '489153684515',
    projectId: 'little-strategy-6837a',
    authDomain: 'little-strategy-6837a.firebaseapp.com',
    databaseURL: 'https://little-strategy-6837a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'little-strategy-6837a.firebasestorage.app',
    measurementId: 'G-8QBHS8G00E',
  );

}