name: game_info_repository
publish_to: none

environment:
  sdk: '^3.6.0'

dependencies:
  flutter_test:
      sdk: flutter
  cloud_firestore: 5.5.1
  firebase_core: 3.8.1
  logging: 1.3.0
  flutter_lints: 5.0.0
  flutter_riverpod: 2.6.1
  domain_entities: 
    path: ../domain_entities
    
dev_dependencies:
  build_runner: 2.4.14
