name: lootbox_repository
publish_to: none

environment: 
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  domain_entities: 
    path: ../domain_entities
  firebase_storage: ^12.3.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  logging: ^1.3.0
  fake_cloud_firestore: ^3.1.0
  mocktail: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
