name: user_remote_repository
publish_to: none

environment: 
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.5.1
  domain_entities: 
    path: ../domain_entities
  firebase_database: ^11.1.6
  firebase_storage: ^12.3.6
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  logging: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
